- server/routes/user.router.js
- server/strategies/user.strategy.js
- src/components/LoginForm/LoginForm.jsx
- src/components/RegisterForm/RegisterForm.jsx
- src/components/UserPage/UserPage.jsx
> Register modifications

- src/components/AdminJobList/AdminJobList.jsx
- src/components/ApproveSubmissions/ApproveSubmissions.jsx
- src/components/PeadyToPostList/ReadyToPostList.jsx
Here's a small component that will make it easy to import the list of APPROVED job postings onto any page.
> Ready to post list

- INSTRUCTIONS.md
- server/routes/campaign.router.js
- server/routes/subs.router.js
- server/routes/template.router.js
- server/server.js
- src/components/AdminDrawerMenu/AdminDrawerMenu.jsx
- src/components/AdminHub/AdminHub.jsx
- src/components/App/App.jsx
- src/components/Campaign/Campaign.jsx
- src/components/EmailTemplate/EmailTemplate.jsx
- src/components/Nav/Nav.css
- src/components/Nav/Nav.jsx
- src/components/Styles/Styles.jsx
- src/components/UserPage/UserPage.jsx
- src/redux/sagas/_root.saga.js
- src/redux/sagas/campaign.saga.js
- src/redux/sagas/getCampaign.saga.js
- src/redux/sagas/sendEmailNow.saga.js
Added a few components and parts - 
routers for campaign and email template, 
sagas for get and post campaigns (get is not functional yet but may not be necessary)
no reducers yet - might add later
Campaign page (formerly UserPage) is properly routed and can save a campaign to MailChimp as well as send one immediately - bear in mind that the template ID, for now, is hardcoded - I'm working on this next
> Feature mailchimp compose

- src/components/AdminHub/AdminHub.jsx
- src/components/NewSubmissionsAlert/NewSubmissionsAlert.jsx
Alert for new Employer added job postings, awaiting approval.
> alert box for new job submissions

- server/routes/job_postings.router.js
- server/routes/posting_age.router.js
- server/routes/search_jobs.router.js
- server/server.js
- src/components/Main/Main.jsx
- src/redux/reducers/_root.reducer.js
- src/redux/reducers/moreRecentJobs.reducer.js
- src/redux/sagas/fetchJobs.saga.js
I wasn't super careful about avoiding changing other stuff, because I didn't think I would push this.
> Sort by age router

- src/components/App/App.css
- src/components/LoginForm/LoginForm.jsx
- src/components/Styles/Styles.jsx
> login page facelift (register next)

- server/modules/emailTemplate.js
Just changed the email header to link to the mailing list sign-up (will need to tie to her dot-com when the time comes)
> added link to email header

- src/components/JobPostingIssuesPage/JobPostingIssuesPage.jsx
- src/redux/sagas/addJobIssue.saga.js
> Feature job issues route edits

- server/routes/template.router.js
- src/components/AdminDrawerMenu/AdminDrawerMenu.jsx
- src/components/Campaign/Campaign.jsx
- src/components/EmailTemplate/EmailTemplate.jsx
- src/components/FinalizeAndSendCampaign/FinalizeAndSendCampaign.jsx
- src/components/Nav/Nav.css
- src/components/Nav/Nav.jsx
- src/components/Styles/Styles.jsx
A few late-night fixes - 
- "template" page is now "New Email" page 
- "Campaign" page nav is gone (naving to it w/o hitting "new email" causes problems anyway)
- added margins to ul in the email - it was too close to the edge
- confirmed a couple links
- cleaned up the "new email" path with unnecessary fields and stuff
- added a history.push to adminhub after email successfully sent (still needs a snackbar)
- party
> Feature email tweaks

- server/routes/employer.router.js
- server/routes/job_postings.router.js
- server/server.js
- src/components/AdminAddJobPage/AdminAddJobPage.jsx
- src/components/Main/Main.css
- src/components/Main/Main.jsx
- src/components/PeadyToPostList/ReadyToPostList.jsx
- src/redux/sagas/approvedPostings.saga.js
- src/redux/sagas/employer.saga.js
some server and other cleanup here and there.
> Modify server 1

- server/routes/job_issues.router.js
- server/routes/job_postings.router.js
- server/routes/search_jobs.router.js
- src/components/EmployerPage/EmployerPage.css
- src/components/EmployerPage/EmployerPage.jsx
- src/components/JobPostingIssuesPage/JobPostingIssuePage.css
- src/components/JobPostingIssuesPage/JobPostingIssuesPage.jsx
> Recaptcha inclusion

- src/components/FinalizeAndSendCampaign/FinalizeAndSendCampaign.jsx
Ternary operator wraps all buttons on final send page. Also,  we should change the header (to something else).
I also added the word "loading" to the loading thingy.
> ternary loading fixed / buttons included

- server/routes/job_postings.router.js
- server/routes/search_jobs.router.js
- src/components/AdminJobList/AdminJobList.jsx
- src/components/AdminJobList/AdminJoblistItem.jsx
- src/components/App/App.jsx
- src/components/EditJobPage/EditJobForm.jsx
- src/components/EditJobPage/EditJobPage.jsx
- src/components/Internships/Internships.jsx
- src/components/Main/Main.jsx
- src/components/PeadyToPostList/ReadyToPostList.jsx
- src/components/RemoteJobs/RemoteJobs.jsx
- src/redux/reducers/_root.reducer.js
- src/redux/reducers/job_to_edit.reducer.js
- src/redux/reducers/jobs.reducer.js
- src/redux/reducers/jobtypes.reducer.js
- src/redux/sagas/_root.saga.js
- src/redux/sagas/addJobIssue.saga.js
- src/redux/sagas/editPosting.saga.js
- src/redux/sagas/employer.saga.js
What is this, even?
Also, it will want a snackbar snack, eventually.
> Feature edit page

- src/components/AdminHub/AdminHub.css
- src/components/AdminHub/AdminHub.jsx
- src/components/App/App.jsx
- src/components/Styles/Styles.jsx
This is a LOT of code on the AdminHub page, but it's just copying the table, changing the columns and the classname. Clean and quick. I'll put them in separate components AFTER the presentation.
I also tweaked a couple small text styling things on that page and may have hit a few other misc sections.
> AdminHub table now responsive (4col lg, 3col md, 2col sm, no table xs)

- src/components/FinalizeAndSendCampaign/FinalizeAndSendCampaign.jsx
> 1153 commit official

- README.md
Only a few, but I'm pushing and putting in pull requests so I don't lose track.
> some readme edits

- src/components/AdminHub/AdminHub.jsx
- src/components/AdminHub/AdminHubFourColTable.jsx
- src/components/AdminHub/AdminHubManualSubEntryForm.jsx
- src/components/AdminHub/AdminHubThreeColTable.jsx
- src/components/AdminHub/AdminHubTwoColTable.jsx
Split AdminHub into a few more components
-manual admin subscriber entry form
-four col table
-three col table (responsive)
-two col table (responsiver)
> components split up in adminhub

- README.md
- server/routes/employer.router.js
- server/routes/grecaptcha.router.js
- server/routes/job_issues.router.js
- server/routes/job_postings.router.js
- src/components/App/App.jsx
- src/components/EmployerPage/EmployerPage.jsx
- src/components/Footer/Footer.jsx
- src/components/JobPostingIssuesPage/JobPostingIssuesPage.jsx
Changed login nav path and got rid of temp login button
> Feature login nav and cleanup

- src/components/JobPostingIssuesPage/JobPostingIssuesPage.jsx
- src/components/Main/Main.jsx
- src/redux/reducers/_root.reducer.js
After my last merge, I saw that there was an error right away on the DOM for a reducer that was no longer defined on the root reducer, so I deleted that and did a bit of code cleanup as well.
> got rid of deleted reducer in root reducer to clear error on DOM and more

- server/routes/feedback.router.js
- server/routes/subs.router.js
- src/components/UnsubFeedbackPage/UnsubFeedbackPage.jsx
- src/redux/sagas/unsubscribe.saga.js
Please review the router I modified, and test after merging.
> Unsubfeedback modifications

- src/components/Main/Main.jsx
- src/components/Reasons/Reasons.jsx
- src/components/UnsubInformation/UnsubInformation.jsx
Small changes, one new component
> unsub component progress.

- server/routes/feedback.router.js
- src/components/UnsubInformation/UnsubInformation.jsx
- src/redux/reducers/unsubscriber.reducer.js
Attempting to count the reasons using a query on the server.
> Count unsub reasons

- src/components/UnsubInformation/UnsubInformation.jsx
- src/redux/reducers/unsubscriber.reducer.js
Should fix rendering lag issue.
> moved exclamations, added loading message

- src/components/UnsubInformation/UnsubInformation.css
- src/components/UnsubInformation/UnsubInformation.jsx
Wanted to try displaying these total unsubscribers in MUI cards. If anyone has feedback as to how to potentially improve the appearance or if we want to revert back to something else that's totally cool!
> Feature unsub info styling

- server/routes/user.router.js
- src/components/AdminHub/AdminHub.jsx
- src/components/LogOutButton/LogOutButton.jsx
- src/components/UserList/UserList.jsx
- src/components/UserList/UserListItem.jsx
- src/redux/reducers/_root.reducer.js
- src/redux/reducers/jobIssues.reducer.js
- src/redux/reducers/setSubsList.reducer.js
- src/redux/reducers/unsubFeedback.reducer.js
- src/redux/reducers/userList.reducer.js
- src/redux/sagas/login.saga.js
- src/redux/sagas/user.saga.js
Option to update admin access level
> Feature admin add access

- src/components/AdminJobList/AdminJoblistItem.jsx
fixing the links on  the admin job list.
> Admin joblink checker

- src/components/FinalizeAndSendCampaign/FinalizeAndSendCampaign.jsx
> replacing hardcoded 1153 on campaign send and cofirm page

- src/components/AdminAddJobPage/AdminAddJobPage.jsx
- src/components/AdminDrawerMenu/AdminDrawerMenu.jsx
- src/components/AdminHub/AdminHub.jsx
- src/components/AdminHub/AdminHubManualSubEntryForm.jsx
- src/components/Campaign/Campaign.jsx
- src/components/EditJobPage/EditJobForm.jsx
- src/components/EmailTemplate/EmailTemplate.jsx
- src/components/EmployerPage/EmployerPage.jsx
- src/components/FinalizeAndSendCampaign/FinalizeAndSendCampaign.jsx
- src/components/JobIssuesReviewPage/JobIssuesReviewItem.jsx
- src/components/JobIssuesReviewPage/JobIssuesReviewPage.jsx
- src/components/JobPostingIssuesPage/JobPostingIssuesPage.jsx
- src/components/Main/Main.jsx
- src/components/UnsubFeedbackPage/UnsubFeedbackPage.jsx
- src/components/UnsubInformation/UnsubInformation.jsx
- src/components/UserList/UserListItem.jsx
There's a lot of code I cleared out here. I tried to make sure I only cleared out unused code and console logs. I didn't do much with EmailTemplate.jsx since I was unsure about the mailchimp code and didn't want to accidentally break anything. I just prioritized client side components to start.
> Feature console log clearout

- src/components/AdminHub/AdminHubFourColTable.jsx
> zip code not found
